@extends('layouts.front.master')

@section('bc', Breadcrumbs::render('set_page_name'))

@section('content')
<div class="container">
    <div class="row">
       <div class="col-md-9">
           <header><h2>Choosing A Page Name For Your Ministry</h2></header>

           <div>
               <p style="margin: 0in 0in 0.0001pt; line-height: 15pt; background: white; font-size: 11pt; font-family: Calibri, sans-serif;"><strong><span style="font-size: 14.0pt; font-family: inherit, serif; color: #1d2129;">What exactly do we mean by this?</span></strong><em><span style="font-size: 14.0pt; font-family: inherit, serif; color: #1d2129;">&nbsp;</span></em></p>
               <p style="margin: 0in 0in 0.0001pt; line-height: 15pt; background: white; font-size: 11pt; font-family: Calibri, sans-serif;"><span style="font-size: 14.0pt; font-family: inherit, serif; color: #1d2129;">&nbsp;</span></p>
               <p style="margin: 0in 0in 0.0001pt; line-height: 15pt; background: white; font-size: 11pt; font-family: Calibri, sans-serif;"><span style="font-size: 14.0pt; font-family: inherit, serif; color: #1d2129;">When you first set up a Ministry for yourself, Find A Ministry gives you a url that looks something like this&hellip;..</span></p>
               <p style="margin: 0in 0in 0.0001pt; line-height: 15pt; background: white; font-size: 11pt; font-family: Calibri, sans-serif;"><span style="font-size: 14.0pt; font-family: inherit, serif; color: #1d2129;">&nbsp;</span></p>
               <p style="margin: 0in 0in 0.0001pt; line-height: 15pt; background: white; font-size: 11pt; font-family: Calibri, sans-serif;"><span style="font-size: 14.0pt; font-family: inherit, serif; color: #1d2129;"><a href="http://www.findaministry.com"><span style="color: #365899; text-decoration: none;">http://www.findaministry.com/FAM123</span></a></span></p>
               <p style="margin: 0in 0in 0.0001pt; line-height: 15pt; background: white; font-size: 11pt; font-family: Calibri, sans-serif;"><span style="font-size: 14.0pt; font-family: inherit, serif; color: #1d2129;">&nbsp;</span></p>
               <p style="margin: 0in 0in 0.0001pt; line-height: 15pt; background: white; font-size: 11pt; font-family: Calibri, sans-serif;"><span style="font-size: 14.0pt; font-family: inherit, serif; color: #1d2129;">Not very easy to remember, and &nbsp;certainly not something you could tell your friends to visit.</span></p>
               <p style="margin: 0in 0in 0.0001pt; line-height: 15pt; background: white; font-size: 11pt; font-family: Calibri, sans-serif;"><span style="font-size: 14.0pt; font-family: inherit, serif; color: #1d2129;">&nbsp;</span></p>
               <p style="margin: 0in 0in 0.0001pt; line-height: 15pt; background: white; font-size: 11pt; font-family: Calibri, sans-serif;"><span style="font-size: 14.0pt; font-family: inherit, serif; color: #1d2129;">However, once your Page has been <a href="{{ route('guides.verify_ministry') }}">VERIFIED</a> you are able to claim your own unique Ministry URL.</span></p>
               <p style="margin: 0in 0in 0.0001pt; line-height: 15pt; background: white; font-size: 11pt; font-family: Calibri, sans-serif;"><span style="font-size: 14.0pt; font-family: inherit, serif; color: #1d2129;">&nbsp;</span></p>
               <p style="margin: 0in 0in 0.0001pt; line-height: 15pt; background: white; font-size: 11pt; font-family: Calibri, sans-serif;"><span style="font-size: 14.0pt; font-family: inherit, serif; color: #1d2129;">So now your Ministry URL can be&nbsp;<strong><a href="https://www.FindaMinistry.com"><span style="color: #365899; text-decoration: none;">www.findaministry.com/YourChosenName</span></a></strong></span></p>
               <p style="margin: 0in 0in 0.0001pt; line-height: 15pt; background: white; font-size: 11pt; font-family: Calibri, sans-serif;"><span style="font-size: 14.0pt; font-family: inherit, serif; color: #1d2129;">&nbsp;</span></p>
               <p style="margin: 0in 0in 0.0001pt; line-height: 15pt; background: white; font-size: 11pt; font-family: Calibri, sans-serif;"><span style="font-size: 14.0pt; font-family: inherit, serif; color: #1d2129;">For example:&nbsp;<a href="https://www.FindAMinistry.com"><span style="color: #365899; text-decoration: none;">http://www.Find A Ministry.com/myPage</span></a></span></p>
               <p style="margin: 0in 0in 0.0001pt; line-height: 15pt; background: white; font-size: 11pt; font-family: Calibri, sans-serif;"><span style="font-size: 14.0pt; font-family: inherit, serif; color: #1d2129;">&nbsp;</span></p>
               <p style="margin: 0in 0in 0.0001pt; line-height: 15pt; background: white; font-size: 11pt; font-family: Calibri, sans-serif;"><strong><em><span style="font-size: 14.0pt; font-family: inherit, serif; color: #1d2129;">According to Find A Ministry Terms &amp; Conditions</span></em></strong></p>
               <p style="margin: 0in 0in 0.0001pt; line-height: 15pt; background: white; font-size: 11pt; font-family: Calibri, sans-serif;"><span style="font-size: 14.0pt; font-family: inherit, serif; color: #1d2129;">&nbsp;</span></p>
               <p style="margin: 0in 0in 0.0001pt; line-height: 15pt; background: white; font-size: 11pt; font-family: Calibri, sans-serif;"><span style="font-size: 14.0pt; font-family: inherit, serif; color: #1d2129;">Ministry Page Names were created to make it easier for people to find Ministry pages and share with others. As a reputable Ministry, your page name should be straightforward and easy to remember.</span></p>
               <p style="margin: 0in 0in 0.0001pt; line-height: 15pt; background: white; font-size: 11pt; font-family: Calibri, sans-serif;"><span style="font-size: 14.0pt; font-family: inherit, serif; color: #1d2129;">&nbsp;</span></p>
               <p style="margin: 0in 0in 0.0001pt; line-height: 15pt; background: white; font-size: 11pt; font-family: Calibri, sans-serif;"><strong><em><span style="font-size: 14.0pt; font-family: inherit, serif; color: #1d2129;">Find A Ministry encourages you to consider the following when creating a page name for your Ministry:</span></em></strong></p>
               <p style="margin: 0in 0in 0.0001pt; line-height: 15pt; background: white; font-size: 11pt; font-family: Calibri, sans-serif;"><span style="font-size: 14.0pt; font-family: inherit, serif; color: #1d2129;">&nbsp;</span></p>
               <ul style="list-style-type: square; margin-bottom: 0in; margin-top: 0px;">
                   <li style="margin: 0in 0in 8pt -0.25in; line-height: 15pt; background: white; font-size: 11pt; font-family: Calibri, sans-serif;"><span style="font-size: 14.0pt; font-family: inherit, serif; color: #1d2129;">Create a name that is as close as possible to your Ministry name (e.g. SteadyWorship).</span> for a Music Ministry</li>
                   <li style="margin: 0in 0in 8pt -0.25in; line-height: 15pt; background: white; font-size: 11pt; font-family: Calibri, sans-serif;"><span style="font-size: 14.0pt; font-family: inherit, serif; color: #1d2129;">If you own the rights to a given name, make it your page name so that others cannot obtain it.</span></li>
                   <li style="margin: 0in 0in 8pt -0.25in; line-height: 15pt; background: white; font-size: 11pt; font-family: Calibri, sans-serif;"><span style="font-size: 14.0pt; font-family: inherit, serif; color: #1d2129;">Page Names can only contain alphanumeric characters (A-Z, 0-9).</span></li>
                   <li style="margin: 0in 0in 8pt -0.25in; line-height: 15pt; background: white; font-size: 11pt; font-family: Calibri, sans-serif;"><span style="font-size: 14.0pt; font-family: inherit, serif; color: #1d2129;">Choose a page name you will be happy with for the long term.&nbsp;<strong>Page Names are not transferable</strong>.</span></li>
                   <li style="margin: 0in 0in 8pt -0.25in; line-height: 15pt; background: white; font-size: 11pt; font-family: Calibri, sans-serif;"><span style="font-size: 14.0pt; font-family: inherit, serif; color: #1d2129;">Your page name must adhere to&nbsp;<strong><em>Find A Ministry&rsquo;s Statement of Rights and Responsibilities.</em></strong> Therefore, you do not choose names that are offensive or have a profane meaning</span></li>
               </ul>
               <p style="margin: 0in 0in 0.0001pt; line-height: 15pt; background: white; font-size: 11pt; font-family: Calibri, sans-serif;"><strong><em><span style="font-size: 14.0pt; font-family: inherit, serif; color: #1d2129;">There are a few things to consider before creating your page names.</span></em></strong></p>
               <p style="margin: 0in 0in 0.0001pt; line-height: 15pt; background: white; font-size: 11pt; font-family: Calibri, sans-serif;"><span style="font-size: 14.0pt; font-family: inherit, serif; color: #1d2129;">&nbsp;</span></p>
               <ul style="list-style-type: square; margin-bottom: 0in; margin-top: 0px;">
                   <li style="margin: 0in 0in 8pt -0.25in; line-height: 15pt; background: white; font-size: 11pt; font-family: Calibri, sans-serif;"><span style="font-size: 14.0pt; font-family: inherit, serif; color: #1d2129;">Once created if can&rsquo;t be changed</span></li>
                   <li style="margin: 0in 0in 8pt -0.25in; line-height: 15pt; background: white; font-size: 11pt; font-family: Calibri, sans-serif;"><span style="font-size: 14.0pt; font-family: inherit, serif; color: #1d2129;">Find A Ministry is indexed by search engines quicker than some websites and therefore your Ministry page could appear in the search results quicker than your website</span></li>
                   <li style="margin: 0in 0in 8pt -0.25in; line-height: 15pt; background: white; font-size: 11pt; font-family: Calibri, sans-serif;"><em><span style="font-size: 14.0pt; font-family: inherit, serif; color: #1d2129;">Make sure you follow their terms &amp; conditions to ensure that you can keep your page names.</span></em></li>
               </ul>
               <p style="margin: 0in 0in 0.0001pt; line-height: 15pt; background: white; font-size: 11pt; font-family: Calibri, sans-serif;"><strong><em><span style="font-size: 14.0pt; font-family: inherit, serif; color: #1d2129;">So now you have decided on your page Name, follow these steps to claim it.</span></em></strong></p>
               <p style="margin: 0in 0in 0.0001pt; line-height: 15pt; background: white; font-size: 11pt; font-family: Calibri, sans-serif;"><span style="font-size: 14.0pt; font-family: inherit, serif; color: #1d2129;">&nbsp;</span></p>
               <p style="margin: 0in 0in 0.0001pt; line-height: 15pt; background: white; font-size: 11pt; font-family: Calibri, sans-serif;"><span style="font-size: 14.0pt; font-family: inherit, serif; color: #1d2129;">Once logged into Find A Ministry follow these simple steps:</span></p>
               <ul style="margin-bottom: 0in; margin-top: 0px;">
                   <li style="margin: 0in 0in 8pt 0.25in; line-height: 15pt; background: white; font-size: 11pt; font-family: Calibri, sans-serif;"><span style="font-size: 14.0pt; font-family: inherit, serif; color: #1d2129;">Go to&nbsp;<a href="{{ route('my_ministries') }}"><span style="color: #365899; text-decoration: none;">www.findaministry.com/my_ministries</span></a></span></li>
                   <li style="margin: 0in 0in 8pt 0.25in; line-height: 15pt; background: white; font-size: 11pt; font-family: Calibri, sans-serif;"><span style="font-size: 14.0pt; font-family: inherit, serif; color: #1d2129;">Select &ldquo;Select <strong><i class="fa fa-pencil"></i> Edit</strong> Button from Dropdown associated with your page</span></li>
                   <li style="margin: 0in 0in 8pt 0.25in; line-height: 15pt; background: white; font-size: 11pt; font-family: Calibri, sans-serif;"><span style="font-size: 14.0pt; font-family: inherit, serif; color: #1d2129;">If your Ministry has been <a
                                   href="{{ route('guides.verify_ministry') }}" target="_blank">VERIFIED</a> you will be able to choose a name .</span></li>
                   <li style="margin: 0in 0in 8pt 0.25in; line-height: 15pt; background: white; font-size: 11pt; font-family: Calibri, sans-serif;"><span style="font-size: 14.0pt; font-family: inherit, serif; color: #1d2129;">Enter your desired page name and click on &ldquo;Submit Page Name&rdquo;</span></li>
                   <li style="margin: 0in 0in 8pt 0.25in; line-height: 15pt; background: white; font-size: 11pt; font-family: Calibri, sans-serif;"><span style="font-size: 14.0pt; font-family: inherit, serif; color: #1d2129;">If it&rsquo;s available, your Ministry page will be updated</span></li>
               </ul>
               <p style="margin: 0in 0in 0.0001pt; line-height: 15pt; background: white; font-size: 11pt; font-family: Calibri, sans-serif;"><strong><span style="font-size: 14.0pt; font-family: inherit, serif; color: #1d2129;">Now you can send out your new Ministry URL &ndash;&nbsp;<a href="{{ route('home') }}"><span style="color: #365899; text-decoration: none;">http://www.Findaministrycom/YourChosenName</span></a></span></strong></p>
               <p style="margin: 0in 0in 0.0001pt; line-height: 15pt; background: white; font-size: 11pt; font-family: Calibri, sans-serif;"><span style="font-size: 14.0pt; font-family: inherit, serif; color: #1d2129;">&nbsp;</span></p>
               <p style="margin: 0in 0in 0.0001pt; line-height: 15pt; background: white; font-size: 11pt; font-family: Calibri, sans-serif;"><strong><span style="font-size: 14.0pt; font-family: inherit, serif; color: #1d2129;">Remember - this won't work for a Page that hasn't been verified.</span></strong></p>
               <p style="margin: 0in 0in 8pt; line-height: 107%; font-size: 11pt; font-family: Calibri, sans-serif;"><span style="font-size: 14.0pt; line-height: 107%;">&nbsp;</span></p>
           </div>
       </div> {{-- End--}}

        <div class="col-md-3">
            @include('partials.sidebar')
        </div>
    </div>
</div>
    @endsection